version: 2.1
orbs:
  python: circleci/python@2.0.3
  ansible: orbss/ansible-playbook@0.0.5

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  ansible-playbook:
    executor: ansible-playbook/default

    steps:
      - checkout
      - ansible/install:
          version: 2.9.23
      - ansible/playbook:
          inventory: ANSIBLE_INVENTORY
          playbook: ansible/playbook.yml
          private-key: ANSIBLE_SSH_KEY

workflows:
  raisetech:
    jobs:
      - cfn-lint
      - ansible-playbook:
          requires:
              - cfn-lint
