version: 2.1
orbs:
  python: circleci/python@2.0.3
  ansible: orbss/ansible-playbook@0.0.5

jobs:
  # cfn-lint:
  #   executor: python/default
  #   steps:
  #     - checkout
  #     - run: pip install cfn-lint
  #     - run:
  #         name: run cfn-lint
  #         command: |
  #           cfn-lint -i W3002 -t cloudformation/*.yml

  ansible-playbook:
    executor: ansible/default
    steps:
      - checkout
      - run:
          name: test
          command: |
            echo ${AWS_FINGERPRINT}
            echo "${AWS_FINGERPRINT}"
      - add_ssh_keys:
          fingerprints:
            - "4e:28:bf:59:42:5f:7d:ff:b3:5c:54:c6:bf:53:bb:0a"
      #       - "${AWS_FINGERPRINT}"
      - ansible/install:
          version: 2.9.23
      - ansible/playbook:
          playbook: ansible/playbook.yml
          playbook-options: "-i ansible/inventory -vvv"

workflows:
  raisetech:
    jobs:
      # - cfn-lint
      # - ansible-playbook:
      #     requires:
      #         - cfn-lint
      - ansible-playbook
